services:
  config-agent:
    build:
      context: ../ermes-agents/agents/config-agent
      dockerfile: Dockerfile
    volumes:
      - ${ERMES_DATA_ROOT}/config-agent/data:/home/user/app/data
      - ${ERMES_DATA_ROOT}/config-agent/training:/home/user/app/training_data
    ports:
      - "9998:9998"

networks:
  default:
    name: ermes

